# Generated by Django 3.2.9 on 2021-11-28 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('met_office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherpayload',
            name='file_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
